global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: recidapp
    static_configs:
      - targets: ["recid_prediction_app_container:9100"]