name: Backend-Lint

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Install golint
        run: |
          cd Backend
          go get -u golang.org/x/lint/golint

      - name: Update PATH
        run: echo "PATH=\$PATH:$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Lint code
        run: golint ./Backend/...