name: Fullstack-Lint

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
      - 'Frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/**'
      - 'Frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

      - name: Lint Backend
        run: |
          golangci-lint run Backend/...

      - name: Lint Frontend
        run: |
          golangci-lint run Frontend/...
